### ISSUE TITLE
I used the same lib name

### ISSUE THREAD

**Issue by TheDev6** [i-e-b/FluentBdd#1]
Hey, your lib has been around way longer and I just realized we have the same lib name when I was searching for mine. My apologies. I can rename mine, link to yours, or other ideas you may have. I'm not too bothered about the two of them as they seem to do different things, but just let me know. thx!

**Comment by i-e-b** [comment]
Not a problem for me -- I haven't touched this code in a few years, and I don't have any intention of publishing it on NuGet.

Good luck with your project :-)
